<?php

/**
 * @file
 * IIIF Data.
 */

/**
 * Implements hook_theme().
 */
function iiif_media_source_theme($existing, $type, $theme, $path) {
  return [
    'iiif_image' => [
      'variables' => [
        'item' => NULL,
        'image' => '',
        'url_params' => NULL,
        'attributes' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_media_source_info_alter().
 */
function template_preprocess_iiif_image(&$variables) {

  $image = $variables['image'];

  $variables['content'] = [
    'image' => [
      '#theme' => 'image',
      '#uri' => $image->getBuiltImageUrl($variables['url_params']),
      '#attributes' => $variables['attributes'],
    ],
  ];

}
