<?php

/**
 * @file
 *
 * Provides IIIF image handling functionality.
 */

declare(strict_types=1);

use Drupal\media_library_media_modify\Form\FileEditForm;

/**
 * Implements hook_theme().
 *
 * This hook is used to define custom theme functions or templates.
 */
function iiif_image_handling_theme($existing, $type, $theme, $path) {

  return [];
}

/**
 * Implements hook_media_source_info_alter().
 *
 * Alters the media source information to add a custom edit form for IIIF images.
 */
function iiif_image_handling_media_source_info_alter(array &$sources): void {
  if (\Drupal::moduleHandler()->moduleExists('media_library_media_modify')) {
    if (empty($sources['iiif_image']['forms']['media_library_media_modify_edit'])) {
      $sources['iiif_image']['forms']['media_library_media_modify_edit'] = FileEditForm::class;
    }
  }
}
