iiif_image_style.style.*:
  type: config_entity
  label: IIIF Image Style
  mapping:
    name:
      type: string
      label: Name
    label:
      type: label
      label: Label
    uuid:
      type: string
    style:
      type: mapping
      label: 'Style Definition'
      mapping:
        region:
          type: string
          label: ''
        region_x:
          type: float
          nullable: true
          label: ''
        region_y:
          type: float
          nullable: true
          label: ''
        region_w:
          type: float
          nullable: true
          label: ''
        region_h:
          type: float
          nullable: true
          label: ''
        size:
          type: string
          label: ''
        size_w:
          type: float
          nullable: true
          label: ''
        size_h:
          type: float
          nullable: true
          label: ''
        size_n:
          type: float
          nullable: true
          label: ''
        rotation:
          type: float
          label: ''
        quality:
          type: string
          label: ''
        format:
          type: string
          label: ''
