iiif_image_style.style.*:
  type: config_entity
  label: IIIF Image Style
  mapping:
    name:
      type: string
      label: Name
    label:
      type: label
      label: Label
    uuid:
      type: string
    effects:
      type: sequence
      sequence:
        type: mapping
        mapping:
          uuid:
            type: uuid
          id:
            type: string
          weight:
            type: integer
          data:
            type: iiif_image_style.effect.[%parent.id]

iiif_image_style.effect.*:
  type: mapping
  label: 'Effect settings'

iiif_image_style.effect.iiif_image_resize:
  type: mapping
  label: 'IIIF Image Settings'
  mapping:
    size_w:
      type: float
      nullable: true
      label: ''
    size_h:
      type: float
      nullable: true
      label: ''
    size_n:
      type: float
      nullable: true
      label: ''

iiif_image_style.effect.iiif_image_settings:
  type: mapping
  label: 'IIIF Image Settings'
  mapping:
    region:
      type: string
      label: ''
    region_x:
      type: float
      nullable: true
      label: ''
    region_y:
      type: float
      nullable: true
      label: ''
    region_w:
      type: float
      nullable: true
      label: ''
    region_h:
      type: float
      nullable: true
      label: ''
    size:
      type: string
      label: ''
    size_w:
      type: float
      nullable: true
      label: ''
    size_h:
      type: float
      nullable: true
      label: ''
    size_n:
      type: float
      nullable: true
      label: ''
    rotation:
      type: float
      label: ''
    quality:
      type: string
      label: ''
    format:
      type: string
      label: ''






iiif_image_style.responsive_image.*:
  type: config_entity
  label: IIIF Responsive Image Style
  mapping:
    id:
      type: string
      label: ID
    label:
      type: required_label
      label: Label
    uuid:
      type: string
    image_style_mappings:
      type: sequence
      label: 'Image style mappings'
      sequence:
        type: mapping
        label: 'Image style mapping'
        mapping:
          # Image mapping type. Either 'sizes' (using the 'sizes' attribute)
          # or 'image_style' (using a single image style to map to this
          # breakpoint).
          image_mapping_type:
            type: string
            label: 'Responsive image mapping type'
          image_mapping:
            type: iiif_responsive_image.image_mapping_type.[%parent.image_mapping_type]
          breakpoint_id:
            type: string
            label: 'Breakpoint ID'
          multiplier:
            type: string
            label: 'Multiplier'
    breakpoint_group:
      type: string
      label: 'Breakpoint group'
    fallback_image_style:
      type: string
      label: 'Fallback image style'

iiif_responsive_image.image_mapping_type.image_style:
  type: string
  label: 'Image style'

iiif_responsive_image.image_mapping_type.sizes:
  type: mapping
  mapping:
    # The value for the sizes attribute as described in the spec:
    # http://www.w3.org/html/wg/drafts/html/master/embedded-content.html#attr-img-sizes
    sizes:
      type: string
      label: 'Sizes attribute'
    sizes_image_styles:
      type: sequence
      label: 'Image styles to be used when using the ''sizes'' attribute'
      sequence:
        type: string
        label: 'Image style'
