iiif_image_style.style.*:
  type: config_entity
  label: IIIF Image Style
  mapping:
    name:
      type: string
      label: Name
    label:
      type: label
      label: Label
    uuid:
      type: string
    style:
      type: mapping
      label: 'Style Definition'
      mapping:
        region:
          type: string
          label: ''
        region_x:
          type: float
          nullable: true
          label: ''
        region_y:
          type: float
          nullable: true
          label: ''
        region_w:
          type: float
          nullable: true
          label: ''
        region_h:
          type: float
          nullable: true
          label: ''
        size:
          type: string
          label: ''
        size_w:
          type: float
          nullable: true
          label: ''
        size_h:
          type: float
          nullable: true
          label: ''
        size_n:
          type: float
          nullable: true
          label: ''
        rotation:
          type: float
          label: ''
        quality:
          type: string
          label: ''
        format:
          type: string
          label: ''

iiif_image_style.responsive_image.*:
  type: config_entity
  label: IIIF Responsive Image Style
  mapping:
    id:
      type: string
      label: ID
    label:
      type: required_label
      label: Label
    uuid:
      type: string
    image_style_mappings:
      type: sequence
      label: 'Image style mappings'
      sequence:
        type: mapping
        label: 'Image style mapping'
        mapping:
          # Image mapping type. Either 'sizes' (using the 'sizes' attribute)
          # or 'image_style' (using a single image style to map to this
          # breakpoint).
          image_mapping_type:
            type: string
            label: 'Responsive image mapping type'
          image_mapping:
            type: string
            label: 'Image style'
          breakpoint_id:
            type: string
            label: 'Breakpoint ID'
          multiplier:
            type: string
            label: 'Multiplier'
    breakpoint_group:
      type: string
      label: 'Breakpoint group'
    fallback_image_style:
      type: string
      label: 'Fallback image style'
