<?php

/**
 * @file
 */

use Drupal\iiif_image_style\Entity\IiifImageStyle;
use Drupal\iiif_media_source\Iiif\IiifImage;

/**
 * Implements hook_theme().
 */
function iiif_image_style_theme($existing, $type, $theme, $path) {
  return [
    'iiif_image_style' => [
      'variables' => [
        'image' => '',
        'iiif_image_style' => '',
        'attributes' => [],
      ],
    ],
  ];
}

/**
 * Prepares variables for iiif_image_style template.
 *
 * Default template: iiif_image_style.
 */
function template_preprocess_iiif_image_style(&$variables) {
  $image = $variables['image'];

  if ($variables['iiif_image_style']) {
    $image_style = IiifImageStyle::load($variables['iiif_image_style']);
    $style_settings = $image_style->getStyle();
    list($style_settings['region_actual'], $style_settings['size_actual']) = IiifImage::processSettings($style_settings);

    $img_url = $image->getBuiltImageUrl(
      $style_settings['region_actual'],
      $style_settings['size_actual'],
      $style_settings['rotation'],
      $style_settings['quality'],
      $style_settings['format']
    );
  }
  // Original image.
  else {
    $img_url = $image->getFullUrl();
  }

  // Grab final url components from the image style, and pass directly to an image formatter.
  // $image->getBuiltImageUrl();
  $variables['content'] = [
    'image' => [
      '#theme' => 'image',
      '#uri' => $img_url,
      '#attributes' => $variables['attributes'],
    ],
  ];
}

/**
 * Gets an array of image styles suitable for using as select list options.
 *
 * @param $include_empty
 *   If TRUE a ' - None - ' option will be inserted in the options array.
 *
 * @return string[]
 *   Array of image styles both key and value are set to style name.
 */
function iiif_image_style_options($include_empty = TRUE) {
  $styles = IiifImageStyle::loadMultiple();
  $options = [];
  if ($include_empty && !empty($styles)) {
    $options[''] = t(' - None - ');
  }
  foreach ($styles as $name => $style) {
    $options[$name] = $style->label();
  }

  if (empty($options)) {
    $options[''] = t('No defined styles');
  }
  return $options;
}
